CSMarketplace/Models/Devices.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;
using System.Globalization;


namespace CSMarketplace.Models
{
    public class Device
    {

        public int DeviceId { get; set; }
        public string DeviceName { get; set; }
        public string DeviceUrl { get; set; }

        [UIHint("tinymce_jquery_full"), AllowHtml]
        public string DeviceDescription { get; set; }
        public Boolean DeviceActive { get; set; }
        public DeviceValidationType DeviceValidation { get; set; }
        public string DeviceIcon { get; set; }
        public string DeviceSelf
        {
            get
            {
                return string.Format(CultureInfo.CurrentCulture,
                    "restapi/devices/{0}", this.DeviceId);
            }
            set { }
        }
        public Nullable<int> VendorID { get; set; }
        public virtual Vendor Vendor { get; set; }

        public Nullable<int> DeviceCateogryID { get; set; }
        public virtual DeviceCategory DeviceCategory { get; set; }

        public virtual ICollection<DeviceEntity> DeviceEntities { get; set; }
        public virtual ICollection<DeviceScreen> DeviceScreens { get; set; }
        public virtual ICollection<DriverVersion> DriverVersions { get; set; }
        public virtual ICollection<ApplicationVersion> ApplicationVersions { get; set; }
        public virtual ICollection<Driver> Drivers { get; set; }

    }


    public enum DeviceValidationType
    {
        [Display(Name = "Validation Pending")]
        Pending,
        [Display(Name = "Validated")]
        Validated,
        [Display(Name = "Not Validated")]
        Notvalidated
    }




   }

CSMarketplace/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CSMarketplace.Models;
using Microsoft.AspNet.Identity;
using Microsoft.WindowsAzure;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using System.Configuration;
using System.IO;
using System.Threading.Tasks;
using System.Security.Claims;

namespace CSMarketplace.Controllers
{
    public class DevicesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Devices
        /*public async Task<ActionResult> Index()
        {
           // var devices = db.Devices.Include(d => d.Vendor);
           // return View(devices.ToList());

            return View(await db.Devices.Include(d => d.Vendor).ToListAsync());
        }*/
        public ActionResult Index(string sortOrder, string currentFilter, string search, int? page)
        {

            ViewBag.CurrentSort = sortOrder;

            if (page == null || page == 0)
            {

                page = 1;

            }


            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }

            ViewBag.CurrentFilter = search;


            if (!String.IsNullOrEmpty(search))
            {
                ViewBag.FilterWord = search;
            }
            else
            {
                ViewBag.FilterWord = "Search inside table below...";
            }

            var devices = from d in db.Devices
                          select d;
            if (!String.IsNullOrEmpty(search))
            {
                devices = devices.Where(d => d.DeviceName.ToUpper().Contains(search.ToUpper())
                                       || d.Vendor.VendorName.ToUpper().Contains(search.ToUpper()));
            }
            else
            {

                devices = devices.Where(d => d.DeviceId > 0);

            }

            switch (sortOrder)
            {
                case "name_desc":
                    devices = devices.OrderByDescending(d => d.DeviceName);
                    ViewBag.NameSortParm = "name_asc";
                    ViewBag.StatusSortParm = "status_desc";
                    ViewBag.VendorSortParm = "vendor_desc";
                    break;
                case "name_asc":
                    devices = devices.OrderBy(d => d.DeviceName);
                    ViewBag.NameSortParm = "name_desc";
                    ViewBag.StatusSortParm = "status_desc";
                    ViewBag.VendorSortParm = "vendor_desc";
                    break;
                case "status_desc":
                    devices = devices.OrderByDescending(d => d.DeviceValidation);
                    ViewBag.NameSortParm = "name_desc";
                    ViewBag.StatusSortParm = "status_asc";
                    ViewBag.VendorSortParm = "vendor_desc";
                    break;
                case "status_asc":
                    devices = devices.OrderBy(d => d.DeviceValidation);
                    ViewBag.NameSortParm = "name_desc";
                    ViewBag.StatusSortParm = "status_desc";
                    ViewBag.VendorSortParm = "vendor_desc";
                    break;
                case "vendor_desc":
                    devices = devices.OrderByDescending(d => d.Vendor.VendorName);
                    ViewBag.NameSortParm = "name_desc";
                    ViewBag.StatusSortParm = "status_desc";
                    ViewBag.VendorSortParm = "vendor_asc";
                    break;
                case "vendor_asc":
                    devices = devices.OrderBy(d => d.Vendor.VendorName);
                    ViewBag.NameSortParm = "name_desc";
                    ViewBag.StatusSortParm = "status_desc";
                    ViewBag.VendorSortParm = "vendor_desc";
                    break;

                default:
                    ViewBag.NameSortParm = "name_desc";
                    ViewBag.StatusSortParm = "status_desc";
                    ViewBag.VendorSortParm = "vendor_desc";

                    break;
            }

            ViewBag.SortOrder = sortOrder;

            ViewBag.PagerNo = Properties.Settings.Default.PagerAdminNo;
            ViewBag.PageID = page;
            ViewBag.ItemsNo = devices.Count();

            int t_PagerNo = ViewBag.PagerNo;
            int t_PageID = ViewBag.PageID;
            int t_ItemsNo = ViewBag.ItemsNo;

            Decimal calculus = (Decimal)devices.Count() / (Decimal)Properties.Settings.Default.PagerAdminNo;
            calculus = Math.Ceiling(calculus);
            int pagesqty = Convert.ToInt32(calculus); ;
            ViewBag.PagesQty = pagesqty;

            if (page == 1)
            {

                ViewBag.PagePrevIndex = 1;
                ViewBag.PageNextIndex = 2;

            }
            else if (page == pagesqty)
            {
                ViewBag.PagePrevIndex = pagesqty - 1;
                ViewBag.PageNextIndex = pagesqty;

            }
            else
            {
                ViewBag.PagePrevIndex = page - 1;
                ViewBag.PageNextIndex = page + 1;

            }

            ViewBag.ItemStartIndex = (page - 1) * Properties.Settings.Default.PagerAdminNo;

            return View(devices.ToList());
        }

        public ActionResult VendorIndex(string id)
        {

            int vendor_id = db.Vendors.Where(v => v.ApplicationUserId == id).First().VendorId;

            var devices = from d in db.Devices select d;

            devices = devices.Where(a => a.VendorID == vendor_id);

            return View(devices.ToList());

        }

        // GET: /Applications/List
        public ActionResult List(int? cat, int? page)
        {

            var devices = from a in db.Devices select a;

            if (cat == null || cat == 0)
            {
                devices = devices.Where(a => a.DeviceValidation == DeviceValidationType.Validated && a.DeviceActive == true);

                ViewBag.currentCategoryIndex = 0;
            }
            else
            {
                devices = devices.Where(a => a.DeviceValidation == DeviceValidationType.Validated && a.DeviceActive == true && a.DeviceCateogryID == cat);
                ViewBag.currentCategoryIndex = cat;
            }


            if (page == null || page == 0)
            {

                page = 1;

            }




            var categories = from c in db.DeviceCategories select c;

            var CategoriesNames = new List<string> { };
            var CategoriesIndexes = new List<int> { };

            foreach (var item in categories)
            {
                CategoriesNames.Add(item.DeviceCategoryName);
                CategoriesIndexes.Add(item.DeviceCategoryId);
            }


            ViewData["CategoriesNames"] = CategoriesNames;
            ViewData["CategoriesIndexes"] = CategoriesIndexes;

            ViewBag.PagerNo = Properties.Settings.Default.PagerNo;
            ViewBag.PageID = page;
            ViewBag.ItemsNo = devices.Count();

            Decimal calculus = devices.Count() / Properties.Settings.Default.PagerNo;
            calculus = Math.Ceiling(calculus);
            int pagesqty = Convert.ToInt32(calculus); ;
            ViewBag.PagesQty = pagesqty;

            if (page == 1)
            {

                ViewBag.PagePrevIndex = 1;
                ViewBag.PageNextIndex = 2;

            }
            else if (page == pagesqty)
            {
                ViewBag.PagePrevIndex = pagesqty - 1;
                ViewBag.PageNextIndex = pagesqty;

            }
            else
            {
                ViewBag.PagePrevIndex = page - 1;
                ViewBag.PageNextIndex = page + 1;

            }

            ViewBag.ItemStartIndex = (page - 1) * Properties.Settings.Default.PagerNo;
              




            return View(devices.ToList());

            //  return View(db.Vendors.ToList());
        }



        // GET: Devices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }


            ViewBag.VendorName = db.Vendors.Find(device.VendorID).VendorName;



            var deviceScreens = db.DeviceScreens.Where(c => c.DeviceID == id).OrderBy(s => s.DeviceScreenSortIndex);

            var deviceImages = new List<string> { };

            foreach (var item in deviceScreens)
            {
                deviceImages.Add(item.DeviceScreenUrl);

            }

            ViewData["deviceImages"] = deviceImages;






            return View(device);
        }

        // GET: Devices/Create
        public ActionResult Create()
        {
            
            var user_id = User.Identity.GetUserId();

            int vendor_id = db.Vendors.Where(v => v.ApplicationUserId == user_id).First().VendorId;

            ViewBag.vendor_id = vendor_id;

            return View();

        }

        // POST: Devices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DeviceId,DeviceName,DeviceDescription")] Device device)
        {

            var user_id = User.Identity.GetUserId();

            int vendor_id = db.Vendors.Where(v => v.ApplicationUserId == user_id).First().VendorId;

            device.VendorID = vendor_id;
            device.DeviceActive = true;
            device.DeviceValidation = DeviceValidationType.Pending;

CSMarketplace/Views/Devices/Create.cshtml
@model CSMarketplace.Models.Device
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Introduce a new device";
    string user_id = User.Identity.GetUserId();
    int vendor_id = ViewBag.vendor_id;
}

@using (Html.BeginForm("Create", "Devices", new { id = "@user_id" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)



    <div class="page-wraper wraper">
        <div class="row">
            <div class="small-12 columns">
                <div class="admin-content clr">
                    <div class="row content-title">
                        <div class="medium-8 columns page-submenu">
                            <h2>@ViewBag.Title</h2>
                        </div>

                        <div class="medium-4 columns">
                            <a href="@Url.Action("VendorIndex", "Devices", new { id = @user_id }, null)" class="right btn third-btn tiny-btn nomargin">back</a>
                        </div>
                    </div>
                    <form>
                        <div class="row">
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>DEVICE NAME</b>
                                @Html.EditorFor(model => model.DeviceName)
                                @Html.ValidationMessageFor(model => model.DeviceName)
                            </div>
                            <div class="large-12 columns end">
                                <b>ICON:</b>
                                <input type="file" id="FileUploader" name="FileUploader" multiple="multiple" />
                            </div>
                            <div class="large-12 columns end">
                                <b>DESCRIPTION</b>
                                @Html.EditorFor(model => model.DeviceDescription)
                                @Html.ValidationMessageFor(model => model.DeviceDescription)
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>

                            <div class="row">
                                <div class="large-4 medium-6 medium-push-6 large-push-8 columns">
                                    <input type="submit" class="btn auto-btn second-btn register-btn" value="Save" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CSMarketplace/Views/Devices/Delete.cshtml
@model CSMarketplace.Models.Device

@{
    ViewBag.Title = "Are you sure you want to delete Device?";
}


<div class="page-wraper wraper">
    <div class="row">
        <div class="large-8 small-12 large-centered columns">
            <div class="page-content">
                <div class="content-title"><h2>@ViewBag.Title</h2> </div>
                <div class="row mr30">
                    <div class="large-12 columns end">
                        <b>DEVICE NAME:</b>
                        @Html.DisplayFor(model => model.DeviceName)
                    </div>
                    <div class="large-12 columns end">
                        <b>VENDOR NAME:</b>
                        @Html.DisplayFor(model => model.Vendor.VendorName)
                    </div>
                    <div class="large-12 columns end">
                        <b>DEVICE STATUS:</b>
                        @Html.DisplayFor(model => model.DeviceValidation)
                    </div>


                </div>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="row">
                        <div class="large-4 medium-6 medium-push-6 large-push-8 columns">
                            <input type="submit" class="btn auto-btn second-btn register-btn" value="Delete" />
                        </div>
                    </div>
                    <div class="row">
                        <div>
                            @Html.ActionLink("Back to List", "Index")
                        </div>
                    </div>

                }



            </div>
        </div>
    </div>
</div>

CSMarketplace/Views/Devices/Details.cshtml
@model CSMarketplace.Models.Device

@{
    ViewBag.Title = "Details";

    var img_source_logo = Model.DeviceIcon;
}



<div class="page-wraper app-details wraper">
    <div class="row">
        <div class="large-8 columns">
            <dl class="tabs">
                <dd><a href="@Url.Action("List", "Applications", null)">Apps</a></dd>
                <dd><a href="@Url.Action("List", "Drivers", null)">Drivers</a></dd>
                <dd class="active"><a href="@Url.Action("List", "Devices", null)">Devices</a></dd>
                <dd><a href="@Url.Action("List", "Vendors", null)">Vendors</a></dd>
            </dl>
        </div>
        <div class="large-8 columns">
            <dl class="tabs" data-tab><dd><p> </p></dd></dl>
        </div>
    </div>
    <div class="row">

        <div class="large-3 columns">
            <div class="row">
                <div class="large-11 medium-4 medium-push-1 columns mr30">
                    <ul class="row side-nav no-bullet">
                        <div class="slide-nav-head"><img src="@img_source_logo" /></div>
                        <li><a href="#" onclick="scrollToElement('#DeviceOverview'); return false;">app overview</a></li>
                        <li><a href="#" onclick="scrollToElement('#DeviceScreenshots'); return false;">Screenshots</a></li>
                        <li><a href="@Url.Action("Details", "Vendors", new { id = Model.VendorID})">About Vendor</a></li>
                        <li><a href="#" onclick="scrollToElement('#DeviceApplications'); return false;">Applications</a></li>
                        <li><a href="#" onclick="scrollToElement('#DeviceDrivers'); return false;">Drivers</a></li>
                    </ul>
                </div>
                <div class="large-11 medium-4 medium-push-3  large-push-1 columns app-details-stats end">
                    <h3>Device website</h3>
                    <div class="stat-number">
                        <p>Click the link below:</p>
                        <p><a href="@Model.DeviceUrl">@Model.DeviceUrl</a></p>
                    </div>
                    <div class="stat-number">
                    </div>

                </div>
            </div>
        </div>

        <div class="large-9 columns">
            <div class="row">
                <div class="large-12 columns text-right end">
                    <dl class="tabs back-btn">
                        <dd><a href="#" onclick="history.go(-1); return false;">Back to home</a></dd>
                    </dl>
                </div>
                <div class="large-12 columns">
                    <div class="content-title">
                        <h1>@Html.DisplayFor(model => model.DeviceName)</h1>
                        <p><strong>Device introduced</strong> by  @ViewBag.VendorName</p>
                        <h2 id="DeviceOverview">Device Overview</h2>
                        <p>@Html.Raw(Model.DeviceDescription)</p>
                    </div>
                </div>
                <div class="large-12 columns" id="DeviceScreenshots">
                    <h3>Device screenshots</h3>
                </div>
                <div class="large-12 columns">
                    <div class="swiper-container mr40 ">
                        <div class="swiper-wrapper">
                            @{
                                var deviceImages = (List<string>)ViewData["deviceImages"];

                            }

                            @for (int ii = 0; ii < deviceImages.Count(); ii++)
                            {

                                String myDeviceScreen = deviceImages.ElementAt(ii);

                                <div class="swiper-slide">
                                    <img src="@myDeviceScreen" width="100%" alt="">
                                </div>

                            }
                        </div>
                        <div class="pagination pagination1"></div>
                    </div>
                </div>

                <div class="large-12 columns" id="DeviceApplications">
                    <h3>Device Applications</h3>
                </div>
                <div class="large-12 columns" id="DeviceDrivers">
                    <h3>Device Drivers</h3>
                </div>




            </div>
        </div>

    </div>

</div>

CSMarketplace/Views/Devices/Edit.cshtml
@model CSMarketplace.Models.Device
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Update Device";
    string user_id = User.Identity.GetUserId();
    
}



@using (Html.BeginForm("Edit", "Devices", new { id = "@user_id" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.DeviceId)
    @Html.HiddenFor(model => model.VendorID)
    @Html.HiddenFor(model => model.DeviceSelf)
    @Html.HiddenFor(model => model.DeviceUrl)
    @Html.HiddenFor(model => model.DeviceIcon)

    <div class="page-wraper wraper">
        <div class="row">
            <div class="small-12 columns">
                <div class="admin-content clr">
                    <div class="row content-title">
                        <div class="medium-8 columns page-submenu">
                            <h2>@ViewBag.Title</h2>
                            <a href="@Url.Action("Index", "DeviceScreens", new { device_id = @Model.DeviceId })">SCREENS MANAGEMENT</a>
                            <a href="@Url.Action("Index", "DeviceEntities", new { device_id = @Model.DeviceId })">DEVICES IDENTIFICATION LIST (NFC&MAC)</a>
                        </div>
                        <div class="medium-4 columns">
                            <a href="@Url.Action("Index", "Devices", null)" class="right btn third-btn tiny-btn nomargin">back</a>
                        </div>
                    </div>
                    <form>
                        <div class="row">
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>ACTIVE:</b>
                                @Html.EditorFor(model => model.DeviceActive)
                                @Html.ValidationMessageFor(model => model.DeviceActive)
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div> 
                            <div class="large-12 columns end">
                                <b>VALIDATION:</b>
                                @Html.EnumDropDownListFor(model => model.DeviceValidation)
                                @Html.ValidationMessageFor(model => model.DeviceValidation)
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div> 
                            <div class="large-12 columns end">
                                <b>DEVICE NAME</b>
                                @Html.EditorFor(model => model.DeviceName)
                                @Html.ValidationMessageFor(model => model.DeviceName)
                            </div>
                            <div class="large-12 columns end">
                                <b>ICON:</b>
                                <input type="file" id="FileUploader" name="FileUploader" multiple="multiple" />
                                <img src="@Html.ValueFor(model => model.DeviceIcon)" />
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div> 
                            <div class="large-12 columns end">
                                <b>CATEGORY:</b>
                                @Html.DropDownListFor(model => model.DeviceCateogryID, ViewBag.Categories as SelectList, "Select category ->")


                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div> 
                            <div class="large-12 columns end">
                                <b>DESCRIPTION</b>
                                @Html.EditorFor(model => model.DeviceDescription)
                                @Html.ValidationMessageFor(model => model.DeviceDescription)
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="row">
                                <div class="large-4 medium-6 medium-push-6 large-push-8 columns">
                                    <input type="submit" class="btn auto-btn second-btn register-btn" value="Save changes" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CSMarketplace/Views/Devices/EditVendor.cshtml
@model CSMarketplace.Models.Device
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Update Device details";
    string user_id = User.Identity.GetUserId();
 
}


@using (Html.BeginForm("EditVendor", "Devices", new { id = "@user_id" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.DeviceId)
    @Html.HiddenFor(model => model.VendorID)
    @Html.HiddenFor(model => model.DeviceSelf)
    @Html.HiddenFor(model => model.DeviceUrl)
    @Html.HiddenFor(model => model.DeviceIcon)
    @Html.HiddenFor(model => model.DeviceValidation)

    <div class="page-wraper wraper">
        <div class="row">
            <div class="small-12 columns">
                <div class="admin-content clr">
                    <div class="row content-title">
                        <div class="medium-8 columns page-submenu">
                            <h2>@ViewBag.Title</h2>
                            <p><a href="@Url.Action("VendorIndex", "DeviceScreens", new { device_id = @Model.DeviceId })">SCREENS MANAGEMENT</a></p>
                        </div>
                        
                        <div class="medium-4 columns">
                            <a href="@Url.Action("VendorIndex", "Devices", new { id = @user_id }, null)" class="right btn third-btn tiny-btn nomargin">back</a>
                        </div>
                    </div>
                    <form>
                        <div class="row">
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>ACTIVE:</b>
                                @Html.EditorFor(model => model.DeviceActive)
                                @Html.ValidationMessageFor(model => model.DeviceActive)
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>VALIDATION:</b>
                                @Html.DisplayFor(model => model.DeviceValidation)                            
                            </div>  
                            <div class="large-12 columns end">
                                <br />
                            </div> 
                            <div class="large-12 columns end">
                                <b>APPLICATION NAME</b>
                                @Html.EditorFor(model => model.DeviceName)
                                @Html.ValidationMessageFor(model => model.DeviceName)
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>ICON:</b>
                                <input type="file" id="FileUploader" name="FileUploader" multiple="multiple" />
                                <img src="@Html.ValueFor(model => model.DeviceIcon)" />
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>CATEGORY:</b>
                              @Html.DropDownListFor(model => model.DeviceCateogryID, ViewBag.Categories as SelectList, "Select category ->")
                              

                             </div> 
                            <div class="large-12 columns end">
                                <br />
                            </div>
 
                            <div class="large-12 columns end">
                                <b>DESCRIPTION</b>
                                @Html.EditorFor(model => model.DeviceDescription)
                                @Html.ValidationMessageFor(model => model.DeviceDescription)
                            </div>

                            <div class="large-12 columns end">
                                <br />
                            </div>

                            <div class="row">
                                <div class="large-4 medium-6 medium-push-6 large-push-8 columns">
                                    <input type="submit" class="btn auto-btn second-btn register-btn" value="Update Device" />
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}