CSMarketplace/Controllers/DeviceCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CSMarketplace.Models;

namespace CSMarketplace.Controllers
{
    public class DeviceCategoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: DeviceCategories
        public ActionResult Index()
        {
            return View(db.DeviceCategories.ToList());
        }

        // GET: DeviceCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeviceCategory deviceCategory = db.DeviceCategories.Find(id);
            if (deviceCategory == null)
            {
                return HttpNotFound();
            }
            return View(deviceCategory);
        }

        // GET: DeviceCategories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DeviceCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DeviceCategoryId,DeviceCategoryName,DeviceCategoryActive,DeviceCategoryIcon")] DeviceCategory deviceCategory)
        {
            if (ModelState.IsValid)
            {
                db.DeviceCategories.Add(deviceCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(deviceCategory);
        }

        // GET: DeviceCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeviceCategory deviceCategory = db.DeviceCategories.Find(id);
            if (deviceCategory == null)
            {
                return HttpNotFound();
            }
            return View(deviceCategory);
        }

        // POST: DeviceCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DeviceCategoryId,DeviceCategoryName,DeviceCategoryActive,DeviceCategoryIcon")] DeviceCategory deviceCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(deviceCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(deviceCategory);
        }

        // GET: DeviceCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeviceCategory deviceCategory = db.DeviceCategories.Find(id);
            if (deviceCategory == null)
            {
                return HttpNotFound();
            }
            return View(deviceCategory);
        }

        // POST: DeviceCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DeviceCategory deviceCategory = db.DeviceCategories.Find(id);

            db.Database.ExecuteSqlCommand("UPDATE Devices SET DeviceCateogryID = null WHERE DeviceCateogryID={0}", id);

            db.DeviceCategories.Remove(deviceCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CSMarketplace/Views/DeviceCategories/Create.cshtml
@model CSMarketplace.Models.DeviceCategory

@{
    ViewBag.Title = "Create new category";
}


@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)



    <div class="page-wraper wraper">
        <div class="row">
            <div class="small-12 columns">
                <div class="admin-content clr">
                    <div class="row content-title">
                        <div class="medium-8 columns"><h2>@ViewBag.Title</h2> </div>
                        <div class="medium-4 columns">
                            <a href="@Url.Action("Index", "DeviceCategories", null)" class="right btn third-btn tiny-btn nomargin">back</a>
                        </div>
                    </div>
                    <form>
                        <div class="small-12 columns">
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>CATEGORY NAME</b>
                                @Html.EditorFor(model => model.DeviceCategoryName)
                                @Html.ValidationMessageFor(model => model.DeviceCategoryName)
                            </div>
                            <div class="large-12 columns end">
                                <b>ACTIVE:</b>
                                @Html.EditorFor(model => model.DeviceCategoryActive)
                                @Html.ValidationMessageFor(model => model.DeviceCategoryActive)
                            </div>

                            <div class="row">
                                <div class="large-4 medium-6 medium-push-6 large-push-8 columns">
                                    <input type="submit" class="btn auto-btn second-btn register-btn" value="Save changes" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CSMarketplace/Views/DeviceCategories/Delete.cshtml
@model CSMarketplace.Models.DeviceCategory

@{
    ViewBag.Title = "Delete Category";
}


@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="page-wraper wraper">


        <div class="row">
            <div class="small-12 columns">
                <div class="admin-content clr">
                    <div class="row content-title ">
                        <div class="medium-8 columns page-submenu"><h2>@ViewBag.Title</h2> </div>

                        <div class="medium-4 columns">
                            <a href="@Url.Action("Index", "DeviceCategories", null)" class="right btn third-btn tiny-btn nomargin">back</a>
                        </div>
                    </div>
                    <form>
                        <div class="row">
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <i>Are you sure you want to delete the following Device Category?</i>

                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>DEVICE CATEGORY NAME:</b>
                                @Html.DisplayFor(model => model.DeviceCategoryName)
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>

                            <div class="row">
                                <div class="large-4 medium-6 medium-push-6 large-push-8 columns">
                                    <input type="submit" class="btn auto-btn second-btn register-btn" value="Confirm" />
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

CSMarketplace/Views/DeviceCategories/Details.cshtml
@model CSMarketplace.Models.DeviceCategory

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DeviceCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeviceCategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceCategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeviceCategoryActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceCategoryActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeviceCategoryIcon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceCategoryIcon)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DeviceCategoryId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CSMarketplace/Views/DeviceCategories/Edit.cshtml
@model CSMarketplace.Models.DeviceCategory

@{
    ViewBag.Title = "Update Category Details";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.DeviceCategoryId)
    @Html.HiddenFor(model => model.DeviceCategoryIcon)


    <div class="page-wraper wraper">
        <div class="row">
            <div class="small-12 columns">
                <div class="admin-content clr">
                    <div class="row content-title">
                        <div class="medium-8 columns page-submenu">
                            <h2>@ViewBag.Title</h2>
                        </div>
                        <div class="medium-4 columns">
                            <a href="@Url.Action("Index", "DeviceCategories", null)" class="right btn third-btn tiny-btn nomargin">back</a>
                        </div>
                    </div>
                    <form>
                        <div class="small-12 columns">
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>DEVICE CATEGORY NAME</b>
                                @Html.EditorFor(model => model.DeviceCategoryName)
                                @Html.ValidationMessageFor(model => model.DeviceCategoryName)
                            </div>
                            <div class="large-12 columns end">
                                <b>ACTIVE:</b>
                                @Html.EditorFor(model => model.DeviceCategoryActive)
                                @Html.ValidationMessageFor(model => model.DeviceCategoryActive)
                            </div>

                            <div class="large-12 columns end">
                                <br />
                            </div>

                            <div class="row">
                                <div class="large-4 medium-6 medium-push-6 large-push-8 columns">
                                    <input type="submit" class="btn auto-btn second-btn register-btn" value="Save changes" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CSMarketplace/Views/DeviceCategories/Index.cshtml
@model IEnumerable<CSMarketplace.Models.DeviceCategory>

@{
    ViewBag.Title = "Devices categories list";
}


<div class="admin-wraper wraper">
    <div class="row">
        <div class="small-12 columns">
            <div class="admin-content clr">
                <div class="row content-title">
                    <div class="medium-8 columns page-submenu">
                        <h2>@ViewBag.Title</h2>
                        @Html.ActionLink("NEW CATEGORY", "Create")
                    </div>
                    <div class="medium-4 columns">
                        <a href="@Url.Action("Index", "Devices", null)" class="right btn third-btn tiny-btn nomargin">back</a>
                    </div>
                </div>

                <div class="row">
                    <div class="small-12 columns">
                        <table rules="all" class="table-apps-list">
                            <thead>
                                <tr>
                                    <th class="text-center" width="50">#</th>
                                    <th width="600">Category Name</th>
                                    <th width="150">Status</th>
                                    <th width="200" class="text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{

                                    var counter = 0;
                                }
                                @foreach (var item in Model)
                                {
                                    counter++;

                                    <tr>
                                        <td class="text-center">@counter</td>
                                        <td>@Html.DisplayFor(modelItem => item.DeviceCategoryName)</td>
                                        @{

                                                var device_category_status = item.DeviceCategoryActive;

                                                if (device_category_status == true)
                                                {
                                                    <td class="validated">Enabled</td>
                                                }
                                                else
                                                {
                                                    <td class="not-validated">Disabled</td>
                                                }

                                        }
                                        <td class="text-center action-column">
                                            <a href="@Url.Action("Edit", "DeviceCategories", new { id = item.DeviceCategoryId })" ><div class="sprite-edit-icon"></div></a>
                                            <a href="@Url.Action("Delete", "DeviceCategories", new { id = item.DeviceCategoryId })" ><div class="sprite-remove-icon"></div></a>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>