CSMarketplace/Models/Applications.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;
using System.Globalization;

namespace CSMarketplace.Models
{
    public class Application
    {

        public int ApplicationId { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationUrl { get; set; }

        [UIHint("tinymce_jquery_full"), AllowHtml]
        public string ApplicationDescription { get; set; }
        public Boolean ApplicationActive { get; set; }
        public ApplicationValidationType ApplicationValidation { get; set; }
        /// <summary>
        /// Path to Application Icon
        /// </summary>
        /// <value>URL</value>
        public string ApplicationLogo { get; set; }
        public string ApplicationSelf
        {
            get
            {
                return string.Format(CultureInfo.CurrentCulture,
                    "restapi/applications/{0}", this.ApplicationId);
            }
            set { }
        }
        public Nullable <int> VendorID { get; set; }        
        public virtual Vendor Vendor { get; set; }

        public Nullable <int> ApplicationCategoryID { get; set; }
        public virtual ApplicationCategory ApplicationCategory { get; set; }

        public virtual ICollection<ApplicationScreen> ApplicationScreens { get; set; }
        public virtual ICollection<ApplicationVersion> ApplicationVersions { get; set; }
    }


    public enum ApplicationValidationType
    {
        [Display(Name = "Validation Pending")]
        Pending,
        [Display(Name = "Validated")]
        Validated,
        [Display(Name = "Not Validated")]
        Notvalidated
    }

}

CSMarketplace/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CSMarketplace.Models;
using Microsoft.AspNet.Identity;
using Microsoft.WindowsAzure;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using System.Configuration;
using System.IO;
using System.Threading.Tasks;
using System.Security.Claims;
 

namespace CSMarketplace.Controllers
{
    public class ApplicationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Applications/
        public ActionResult Index(string sortOrder, string currentFilter, string search, int? page)
        {

            ViewBag.CurrentSort = sortOrder;

            if (page == null || page == 0)
            {

                page = 1;

            }


            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }

            ViewBag.CurrentFilter = search;


            if (!String.IsNullOrEmpty(search))
            {
                ViewBag.FilterWord = search;
            }else{
                ViewBag.FilterWord = "Search inside table below...";
            }

            var applications = from a in db.Applications
                           select a;
            if (!String.IsNullOrEmpty(search))
            {
                applications = applications.Where(a => a.ApplicationName.ToUpper().Contains(search.ToUpper())
                                       || a.Vendor.VendorName.ToUpper().Contains(search.ToUpper()));
            }
            else
            {

                applications = applications.Where(a=>a.ApplicationId > 0);

            }

            switch (sortOrder)
            {
                case "name_desc":
                    applications = applications.OrderByDescending(a => a.ApplicationName);
                    ViewBag.NameSortParm = "name_asc";
                    ViewBag.StatusSortParm = "status_desc";
                    ViewBag.VendorSortParm = "vendor_desc";
                    break;
                case "name_asc":
                    applications = applications.OrderBy(a => a.ApplicationName);
                    ViewBag.NameSortParm = "name_desc";
                    ViewBag.StatusSortParm = "status_desc";
                    ViewBag.VendorSortParm = "vendor_desc";
                    break;
                case "status_desc":
                    applications = applications.OrderByDescending(a => a.ApplicationValidation);
                    ViewBag.NameSortParm = "name_desc";
                    ViewBag.StatusSortParm = "status_asc";
                    ViewBag.VendorSortParm = "vendor_desc";
                    break;
                case "status_asc":
                    applications = applications.OrderBy(a => a.ApplicationValidation);
                    ViewBag.NameSortParm = "name_desc";
                    ViewBag.StatusSortParm = "status_desc";
                    ViewBag.VendorSortParm = "vendor_desc";
                    break;
                case "vendor_desc":
                    applications = applications.OrderByDescending(a => a.Vendor.VendorName);
                    ViewBag.NameSortParm = "name_desc";
                    ViewBag.StatusSortParm = "status_desc";
                    ViewBag.VendorSortParm = "vendor_asc";
                    break;
                case "vendor_asc":
                    applications = applications.OrderBy(a => a.Vendor.VendorName);
                    ViewBag.NameSortParm = "name_desc";
                    ViewBag.StatusSortParm = "status_desc";
                    ViewBag.VendorSortParm = "vendor_desc";
                    break;

                default:
                      ViewBag.NameSortParm = "name_desc";
                      ViewBag.StatusSortParm = "status_desc";
                      ViewBag.VendorSortParm = "vendor_desc";
           
                    break;
            }

            ViewBag.SortOrder = sortOrder;

            ViewBag.PagerNo = Properties.Settings.Default.PagerAdminNo;
            ViewBag.PageID = page;
            ViewBag.ItemsNo = applications.Count();

            Decimal calculus = (Decimal)applications.Count() / (Decimal) Properties.Settings.Default.PagerAdminNo;
            calculus = Math.Ceiling(calculus);
            int pagesqty = Convert.ToInt32(calculus); ;
            ViewBag.PagesQty = pagesqty;

            if (page == 1)
            {

                ViewBag.PagePrevIndex = 1;
                ViewBag.PageNextIndex = 2;

            }
            else if (page == pagesqty)
            {
                ViewBag.PagePrevIndex = pagesqty - 1;
                ViewBag.PageNextIndex = pagesqty;

            }
            else
            {
                ViewBag.PagePrevIndex = page - 1;
                ViewBag.PageNextIndex = page + 1;

            }

            ViewBag.ItemStartIndex = (page - 1) * Properties.Settings.Default.PagerAdminNo;
            
            return View(applications.ToList());
        }

        public ActionResult VendorIndex(string id)
        {

            int vendor_id = db.Vendors.Where(v => v.ApplicationUserId == id).First().VendorId;

            var applications = from a in db.Applications select a;

            applications = applications.Where(a => a.VendorID == vendor_id);

            return View(applications.ToList());

        }

        // GET: /Applications/List
        public ActionResult List(int? cat,int? page)
        {
            var applications = from a in db.Applications select a;

            if (cat == null || cat == 0)
            {
                applications = applications.Where(a => a.ApplicationValidation == ApplicationValidationType.Validated && a.ApplicationActive == true);

                ViewBag.currentCategoryIndex = 0;
            }
            else
            {
                applications = applications.Where(a => a.ApplicationValidation == ApplicationValidationType.Validated && a.ApplicationActive == true && a.ApplicationCategoryID == cat);
                ViewBag.currentCategoryIndex = cat;
            }


            if (page == null || page == 0)
            {

                page = 1;

            }



            //applications = applications.Concat(applications);
         
            var categories = from c in db.ApplicationCategories select c;

            var CategoriesNames = new List<string> { };
            var CategoriesIndexes = new List<int> { }; 

             foreach(var item in categories){
                 if (item.ApplicationCategoryActive == true)
                 {
                     CategoriesNames.Add(item.ApplicationCategoryName);
                     CategoriesIndexes.Add(item.ApplicationCategoryId);
                 }
                 
             }


             ViewData["CategoriesNames"] = CategoriesNames;
             ViewData["CategoriesIndexes"] = CategoriesIndexes;

             ViewBag.PagerNo = Properties.Settings.Default.PagerNo;
             ViewBag.PageID = page;
             ViewBag.ItemsNo = applications.Count();

             Decimal calculus = applications.Count() / Properties.Settings.Default.PagerNo;
             calculus=Math.Ceiling(calculus);
             int pagesqty = Convert.ToInt32(calculus); ;
             ViewBag.PagesQty = pagesqty;
              
              if (page == 1) {

                  ViewBag.PagePrevIndex = 1;
                  ViewBag.PageNextIndex = 2;

              }
              else if (page == pagesqty)
              {
                  ViewBag.PagePrevIndex = pagesqty-1;
                  ViewBag.PageNextIndex = pagesqty;

              }
              else
              {
                  ViewBag.PagePrevIndex = page - 1;
                  ViewBag.PageNextIndex = page + 1;

              }

              ViewBag.ItemStartIndex = (page - 1) * Properties.Settings.Default.PagerNo;
              



            return View(applications.ToList());

            //  return View(db.Vendors.ToList());
        }



        // GET: /Applications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }




            ViewBag.VendorName = db.Vendors.Find(application.VendorID).VendorName;



            var applicationScreens = db.ApplicationScreens.Where(c => c.ApplicationID == id).OrderBy(s => s.ApplicationScreenSortIndex);

            var appImages = new List<string> { };

            foreach (var item in applicationScreens)
            {
                appImages.Add(item.ApplicationScreenUrl);
               
            }

            ViewData["appImages"] = appImages;
           


            return View(application);
        }

        // GET: /Applications/View/5
        public ActionResult View(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }




            ViewBag.VendorName = db.Vendors.Find(application.VendorID).VendorName;



            var applicationScreens = db.ApplicationScreens.Where(c => c.ApplicationID == id).OrderBy(s => s.ApplicationScreenSortIndex);

            var appImages = new List<string> { };

            foreach (var item in applicationScreens)
            {
                appImages.Add(item.ApplicationScreenUrl);

            }

            ViewData["appImages"] = appImages;

CSMarketplace/Views/Applications/Create.cshtml
@model CSMarketplace.Models.Application
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Register New Application";
    string user_id = User.Identity.GetUserId();
    int vendor_id = ViewBag.vendor_id;

   // Model.ApplicationVendorID = vendor_id;
    
}


@using (Html.BeginForm("Create", "Applications", new { id = "@user_id" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
   


    <div class="page-wraper wraper">
        <div class="row">
            <div class="small-12 columns">
                <div class="admin-content clr">
                    <div class="row content-title">
                        <div class="medium-8 columns  page-submenu">
                            <h2>@ViewBag.Title</h2>
                        </div>

                        <div class="medium-4 columns">
                            <a href="@Url.Action("VendorIndex", "Applications", new { id = @user_id }, null)" class="right btn third-btn tiny-btn nomargin">back</a>
                        </div>
                    </div>
                    <form>
                        <div class="row">
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>APPLICATION NAME</b>
                                @Html.EditorFor(model => model.ApplicationName)
                                @Html.ValidationMessageFor(model => model.ApplicationName)
                            </div>                         
                            <div class="large-12 columns end">
                                <b>ICON:</b>
                                <input type="file" id="FileUploader" name="FileUploader" multiple="multiple" />
                            </div>
                            <div class="large-12 columns end">
                                <b>APPLICATION ARCHIVE FILE (.ZIP):</b>
                                <input type="file" id="FileUploader2" name="FileUploader2" multiple="multiple" />
                            </div>
                            <div class="large-12 columns end">
                                <b>DESCRIPTION</b>
                                @Html.EditorFor(model => model.ApplicationDescription)
                                @Html.ValidationMessageFor(model => model.ApplicationDescription)
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>

                            <div class="row">
                                <div class="large-4 medium-6 medium-push-6 large-push-8 columns">
                                    <input type="submit" class="btn auto-btn second-btn register-btn" value="Submit" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}










@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CSMarketplace/Views/Applications/Delete.cshtml
@model CSMarketplace.Models.Application

@{
    ViewBag.Title = "Delete Application";
}

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="page-wraper wraper">


        <div class="row">
            <div class="small-12 columns">
                <div class="admin-content clr">
                    <div class="row content-title ">
                        <div class="medium-8 columns page-submenu"><h2>@ViewBag.Title</h2> </div>

                        <div class="medium-4 columns">
                            <a href="@Url.Action("Index", "Applications", null)" class="right btn third-btn tiny-btn nomargin">back</a>
                        </div>
                    </div>
                    <form>
                        <div class="row">
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <i>Are you sure you want to delete the following Application?</i>

                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>APPLICATION NAME:</b>
                                @Html.DisplayFor(model => model.ApplicationName)
                            </div>
                            <div class="large-12 columns end">
                                <b>VENDOR NAME:</b>
                                @Html.DisplayFor(model => model.Vendor.VendorName)
                            </div>
                            <div class="large-12 columns end">
                                <b>APPLICATION STATUS:</b>
                                @Html.DisplayFor(model => model.ApplicationValidation)
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>

                            <div class="row">
                                <div class="large-4 medium-6 medium-push-6 large-push-8 columns">
                                    <input type="submit" class="btn auto-btn second-btn register-btn" value="Confirm" />
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

CSMarketplace/Views/Applications/Details.cshtml
@model CSMarketplace.Models.Application

@{
    ViewBag.Title = "Details";


    var img_source_logo = Model.ApplicationLogo;
}

<div class="page-wraper app-details wraper">
    <div class="row">
        <div class="large-8 columns">
            <dl class="tabs">
                <dd class="active"><a href="@Url.Action("List", "Applications", null)">Apps</a></dd>
                <dd><a href="@Url.Action("List", "Drivers", null)">Drivers</a></dd>
                <dd><a href="@Url.Action("List", "Devices", null)">Devices</a></dd>
                <dd><a href="@Url.Action("List", "Vendors", null)">Vendors</a></dd>
            </dl>
        </div>
        <div class="large-8 columns">
            <dl class="tabs" data-tab><dd><p> </p></dd></dl>
</div>
    </div>
    <div class="row">
        
        <div class="large-3 columns">
            <div class="row">
                <div class="large-11 medium-4 medium-push-1 columns mr30">
                    <ul class="row side-nav no-bullet">
                        <div class="slide-nav-head"><img src="@img_source_logo" /></div>
                        <li><a href="#" onclick="scrollToElement('#ApplicationOverview'); return false;">app overview</a></li>
                        <li><a href="#" onclick="scrollToElement('#ApplicationScreenshots'); return false;">Screenshots</a></li>
                        <li><a href="@Url.Action("Details", "Vendors", new { id = Model.VendorID})">About Vendor</a></li>
                    </ul>
                </div>

            </div>
        </div>

        <div class="large-9 columns">
            <div class="row">
                <div class="large-12 columns text-right end">
                    <dl class="tabs back-btn">
                        <dd><a href="#" onclick="history.go(-1); return false;">Back to home</a></dd>
                    </dl>
                </div>
                <div class="large-12 columns">
                    <div class="content-title">
                        <h1>@Html.DisplayFor(model => model.ApplicationName)</h1>
                        <p><strong>Application developed</strong> by  @ViewBag.VendorName</p>
                        <h2 id="ApplicationOverview">Application Overview</h2>
                        <p>@Html.Raw(Model.ApplicationDescription)</p>
                    </div>
                </div>
                <div class="large-12 columns" id="ApplicationScreenshots">
                    <h3>Application screenshots</h3>
                </div>
                <div class="large-12 columns">
                    <div class="swiper-container mr40 ">
                        <div class="swiper-wrapper">
                            @{
                                var appImages = (List<string>)ViewData["appImages"];
                                
                            }

                            @for (int ii = 0; ii < appImages.Count(); ii++)
                            {

                                String myAppScreen = appImages.ElementAt(ii);
                                                             
                                <div class="swiper-slide">
                                    <img src="@myAppScreen" width="100%" alt="">
                                </div>

                            }
                        </div>
                        <div class="pagination pagination1"></div>
                    </div>
                </div>



        

            </div>
        </div>

    </div>

</div>

CSMarketplace/Views/Applications/Edit.cshtml
@model CSMarketplace.Models.Application
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Update Application";
    string user_id = User.Identity.GetUserId();
 
}


@using (Html.BeginForm("Edit", "Applications", new { id = "@user_id" }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.ApplicationId)
    @Html.HiddenFor(model => model.VendorID)
    @Html.HiddenFor(model => model.ApplicationSelf)
    @Html.HiddenFor(model => model.ApplicationUrl)
    @Html.HiddenFor(model => model.ApplicationLogo)

    <div class="page-wraper wraper">
        <div class="row">
            <div class="small-12 columns">
                <div class="admin-content clr">
                    <div class="row content-title">
                        <div class="medium-8 columns page-submenu">
                            <h2>@ViewBag.Title</h2>
                            <a href="@Url.Action("Index", "ApplicationScreens", new { application_id = @Model.ApplicationId })">SCREENS MANAGEMENT</a>
                        </div>
                        <div class="medium-4 columns">
                            <a href="@Url.Action("Index", "Applications", null)" class="right btn third-btn tiny-btn nomargin">back</a>
                        </div>
                    </div>
                    <form>
                        <div class="row">
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>ACTIVE:</b>
                                @Html.EditorFor(model => model.ApplicationActive)
                                @Html.ValidationMessageFor(model => model.ApplicationActive)
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>VALIDATION:</b>
                                @Html.EnumDropDownListFor(model => model.ApplicationValidation)
                                @Html.ValidationMessageFor(model => model.ApplicationValidation)
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>   
                            <div class="large-12 columns end">
                                <b>APPLICATION NAME</b>
                                @Html.EditorFor(model => model.ApplicationName)
                                @Html.ValidationMessageFor(model => model.ApplicationName)
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>ICON:</b>
                                <input type="file" id="FileUploader" name="FileUploader" multiple="multiple" />
                                <img src="@Html.ValueFor(model => model.ApplicationLogo)" />
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>CATEGORY:</b>
                              @Html.DropDownListFor(model => model.ApplicationCategoryID, ViewBag.Categories as SelectList, "Select category ->")
                              

                             </div> 
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>APPLICATION ARCHIVE FILE (.ZIP):</b>
                                <input type="file" id="FileUploader2" name="FileUploader2" multiple="multiple" />
                                <i>ARCHIVE LINK: <a href="@Html.ValueFor(model => model.ApplicationUrl)">@Html.ValueFor(model => model.ApplicationUrl)</a></i>
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>DESCRIPTION</b>
                                @Html.EditorFor(model => model.ApplicationDescription)
                                @Html.ValidationMessageFor(model => model.ApplicationDescription)
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>

                            <div class="row">
                                <div class="large-4 medium-6 medium-push-6 large-push-8 columns">
                                    <input type="submit" class="btn auto-btn second-btn register-btn" value="Save changes" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CSMarketplace/Views/Applications/VendorIndex.cshtml
@model IEnumerable<CSMarketplace.Models.Application>

@{
    ViewBag.Title = "Applications List";
}

<div class="admin-wraper wraper">
    <div class="row">
        <div class="small-12 columns">
            <div class="admin-content clr">
                <div class="row content-title">                
                        <div class="medium-8 columns  page-submenu">
                            <h2>Applications list</h2>
                            <a href="@Url.Action("Create", "Applications", null)">REGISTER NEW APPLICATION</a>
                        </div>

                </div>

                <div class="row">
                    <div class="small-12 columns">
                        <table rules="all" class="table-apps-list">
                            <thead>
                                <tr>
                                    <th class="text-center" width="50">#</th>
                                    <th width="500">Name</th>
                                    <th width="300">Status</th>
                                    <th width="200" class="text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{

                                        var counter = 0;
                                }
                                @foreach (var item in Model)
                                {
                                    counter++;


                                <tr>
                                    <td class="text-center">1</td>
                                    <td>@Html.DisplayFor(modelItem => item.ApplicationName)</td>

                                    @{
                                        
                                            var app_status = item.ApplicationValidation.ToString();



                                            if (app_status == "Pending")
                                            {

                                                <td class="pending">Pending</td>

                                            }
                                            else if (app_status == "Notvalidated")
                                            {
                                                <td class="not-validated">Not validated</td>

                                            }
                                            else if (app_status == "Validated")
                                            {
                                                <td class="validated">Validated</td>

                                            }
                                        
                                    }

                                  
                                    <td class="text-center action-column">
                                        <a href="@Url.Action("EditVendor", "Applications", new { id = item.ApplicationId })"><div class="sprite-edit-icon"></div></a>
                                    </td>
                                </tr>
    
    
                                }
   
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>