CSMarketplace/Controllers/ApplicationCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CSMarketplace.Models;

namespace CSMarketplace.Controllers
{
    public class ApplicationCategoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ApplicationCategories
        public ActionResult Index()
        {
            return View(db.ApplicationCategories.ToList());
        }

        // GET: ApplicationCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationCategory applicationCategory = db.ApplicationCategories.Find(id);
            if (applicationCategory == null)
            {
                return HttpNotFound();
            }
            return View(applicationCategory);
        }

        // GET: ApplicationCategories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ApplicationCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ApplicationCategoryId,ApplicationCategoryName,ApplicationCategoryActive,ApplicationCategoryIcon")] ApplicationCategory applicationCategory)
        {
            if (ModelState.IsValid)
            {
                db.ApplicationCategories.Add(applicationCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(applicationCategory);
        }

        // GET: ApplicationCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationCategory applicationCategory = db.ApplicationCategories.Find(id);
            if (applicationCategory == null)
            {
                return HttpNotFound();
            }
            return View(applicationCategory);
        }

        // POST: ApplicationCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ApplicationCategoryId,ApplicationCategoryName,ApplicationCategoryActive,ApplicationCategoryIcon")] ApplicationCategory applicationCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicationCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicationCategory);
        }

        // GET: ApplicationCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationCategory applicationCategory = db.ApplicationCategories.Find(id);
            if (applicationCategory == null)
            {
                return HttpNotFound();
            }
            return View(applicationCategory);
        }

        // POST: ApplicationCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ApplicationCategory applicationCategory = db.ApplicationCategories.Find(id);

            db.Database.ExecuteSqlCommand("UPDATE Applications SET ApplicationCategoryID = null WHERE ApplicationCategoryID={0}", id);

            db.ApplicationCategories.Remove(applicationCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CSMarketplace/Views/ApplicationCategories/Create.cshtml
@model CSMarketplace.Models.ApplicationCategory

@{
    ViewBag.Title = "Create a New Category";
}


@using (Html.BeginForm())
{
   
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)



    <div class="page-wraper wraper">
        <div class="row">
            <div class="small-12 columns">
                <div class="admin-content clr">
                    <div class="row content-title ">
                        <div class="medium-8 columns page-submenu"><h2>@ViewBag.Title</h2> </div>

                        <div class="medium-4 columns">
                            <a href="@Url.Action("Index", "ApplicationCategories", null)" class="right btn third-btn tiny-btn nomargin">back</a>
                        </div>
                    </div>
                    <form>
                        <div class="row">
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>CATEGORY NAME</b>
                                @Html.EditorFor(model => model.ApplicationCategoryName)
                                @Html.ValidationMessageFor(model => model.ApplicationCategoryName)
                            </div>
                            <div class="large-12 columns end">
                                <b>ACTIVE:</b>
                                @Html.EditorFor(model => model.ApplicationCategoryActive)
                                @Html.ValidationMessageFor(model => model.ApplicationCategoryActive)
                            </div>

                            <div class="row">
                                <div class="large-4 medium-6 medium-push-6 large-push-8 columns">
                                    <input type="submit" class="btn auto-btn second-btn register-btn" value="Save changes" />
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CSMarketplace/Views/ApplicationCategories/Delete.cshtml
@model CSMarketplace.Models.ApplicationCategory

@{
    ViewBag.Title = "Delete Category";
}


@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="page-wraper wraper">


        <div class="row">
            <div class="small-12 columns">
                <div class="admin-content clr">
                    <div class="row content-title ">
                        <div class="medium-8 columns page-submenu"><h2>@ViewBag.Title</h2> </div>

                        <div class="medium-4 columns">
                            <a href="@Url.Action("Index", "ApplicationCategories", null)" class="right btn third-btn tiny-btn nomargin">back</a>
                        </div>
                    </div>
                    <form>
                        <div class="row">
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <i>Are you sure you want to delete the following Application Category?</i>
                               
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>APPLICATION CATEGORY NAME:</b>
                                @Html.DisplayFor(model => model.ApplicationCategoryName)
                            </div>
                            <div class="large-12 columns end">
                                <br />
                            </div>

                            <div class="row">
                                <div class="large-4 medium-6 medium-push-6 large-push-8 columns">
                                    <input type="submit" class="btn auto-btn second-btn register-btn" value="Confirm" />
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

CSMarketplace/Views/ApplicationCategories/Details.cshtml
@model CSMarketplace.Models.ApplicationCategory

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ApplicationCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationCategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationCategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationCategoryActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationCategoryActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationCategoryIcon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationCategoryIcon)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ApplicationCategoryId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CSMarketplace/Views/ApplicationCategories/Edit.cshtml
@model CSMarketplace.Models.ApplicationCategory

@{
    ViewBag.Title = "Update Category Details";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.ApplicationCategoryId)
    @Html.HiddenFor(model => model.ApplicationCategoryIcon)


    <div class="page-wraper wraper">
        <div class="row">
            <div class="small-12 columns">
                <div class="admin-content clr">
                    <div class="row content-title">
                        <div class="medium-8 columns page-submenu">
                            <h2>@ViewBag.Title</h2>
                        </div>

                        <div class="medium-4 columns">
                            <a href="@Url.Action("Index", "ApplicationCategories", null)" class="right btn third-btn tiny-btn nomargin">back</a>
                        </div>
                    </div>
                    <form>
                        <div class="row">
                            <div class="large-12 columns end">
                                <br />
                            </div>
                            <div class="large-12 columns end">
                                <b>APPLICATION CATEGORY NAME</b>
                                @Html.EditorFor(model => model.ApplicationCategoryName)
                                @Html.ValidationMessageFor(model => model.ApplicationCategoryName)
                            </div>
                            <div class="large-12 columns end">
                                <b>ACTIVE:</b>
                                @Html.EditorFor(model => model.ApplicationCategoryActive)
                                @Html.ValidationMessageFor(model => model.ApplicationCategoryActive)
                            </div>
                           
                            <div class="large-12 columns end">
                                <br />
                            </div>

                            <div class="row">
                                <div class="large-4 medium-6 medium-push-6 large-push-8 columns">
                                    <input type="submit" class="btn auto-btn second-btn register-btn" value="Save changes" />
                                </div>
                            </div>
   
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CSMarketplace/Views/ApplicationCategories/Index.cshtml
@model IEnumerable<CSMarketplace.Models.ApplicationCategory>

@{
    ViewBag.Title = "Applications categories list";
}

<div class="admin-wraper wraper">
    <div class="row">
        <div class="small-12 columns">
            <div class="admin-content clr">
                <div class="row content-title">
                    <div class="medium-8 columns page-submenu">
                        <h2>@ViewBag.Title</h2>
                        @Html.ActionLink("NEW CATEGORY", "Create")
                    </div>

                    <div class="medium-4 columns">                   
                        <a href="@Url.Action("Index", "Applications", null)" class="right btn third-btn tiny-btn nomargin">back</a>
                    </div>
                </div>

                <div class="row">
                    <div class="small-12 columns">
                        <table rules="all" class="table-apps-list">
                            <thead>
                                <tr>
                                    <th class="text-center" width="50">#</th>
                                    <th width="600">Category Name</th>
                                    <th width="150">Status</th>
                                    <th width="200" class="text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{

                                    var counter = 0;
                                }
                                @foreach (var item in Model)
                                {
                                    counter++;

                                    <tr>
                                        <td class="text-center">@counter</td>
                                        <td>@Html.DisplayFor(modelItem => item.ApplicationCategoryName)</td>                                     
                                        @{

                                                var app_category_status = item.ApplicationCategoryActive;

                                                if (app_category_status == true)
                                                {
                                                    <td class="validated">Enabled</td>
                                                }
                                                else
                                                {
                                                    <td class="not-validated">Disabled</td>
                                                }

}
                                        <td class="text-center action-column">
                                            <a href="@Url.Action("Edit", "ApplicationCategories", new { id = item.ApplicationCategoryId })" ><div class="sprite-edit-icon"></div></a>
                                            <a href="@Url.Action("Delete", "ApplicationCategories", new { id = item.ApplicationCategoryId })"><div class="sprite-remove-icon"></div></a>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>